version: "3.7"
services:
  api:
    build:
      context: ./api
      target: prod
    ports:
      - 3000:3000
    environment:
      - ENV
      - LAMBDA_TASK_ROOT
      - AWS_EXECUTION_ENV
      - SERVER_PORT
      - ENABLE_CORS
      - DATABASE_HOST
      - DATABASE_PORT
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - COGNITO_POOL_ID
  client:
    build:
      context: ./front
      target: prod
    ports:
      - 80:80
    environment:
      - ENV
  graph-db:
    image: tianon/true
    restart: "no"
    depends_on:
      - ratel
      - alpha
      - zero
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD

  zero:
    image: dgraph/dgraph:v20.03.0
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:v20.03.0
    ports:
      - 8070:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:v20.03.0
    ports:
      - 8000:8000
    command: dgraph-ratel

