version: '3'
services:
  api:
    build: ./api
    ports:
      - 3000:3000
  client:
    build: ./front
    ports:
      - 80:80
  graph-db:
    image: tianon/true
    restart: "no"
    depends_on:
      - ratel
      - alpha
      - zero
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "6379:6379"
    env_file: .env

  zero:
    image: dgraph/dgraph:v20.03.0
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:v20.03.0
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8070:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:v20.03.0
    ports:
      - 8000:8000
    command: dgraph-ratel

