type User {
  id: ID!
  email: String! @search(by: [exact, trigram])
  authData: AuthData @hasInverse(field: user)
}

type AuthProvider {
  id: ID!
  name: String! @search(by: [exact])
}

type AuthData {
  id: ID!
  provider: AuthProvider!
  sub: String! @id
  user: User @hasInverse(field: authData)
}
